### ISSUE TITLE
Error when opening an image by passing full path

### ISSUE THREAD

**Issue by andresmrm** [karlch/vimiv#21]
I'm getting an error when opening an image by passing full path:

	$ vimiv /tmp/dark_avatar.png
	Traceback (most recent call last):
	  File "/usr/bin/vimiv", line 8, in <module>
		sys.exit(vimiv.main())
	  File "/usr/lib/python3.5/site-packages/vimiv/main.py", line 44, in main
		paths, index = populate(args, recursive, shuffle_paths)
	  File "/usr/lib/python3.5/site-packages/vimiv/fileactions.py", line 59, in populate
		error, args = populate_single(single, recursive)
	  File "/usr/lib/python3.5/site-packages/vimiv/fileactions.py", line 31, in populate_single
		pos = args.index(arg)
	ValueError: '/tmp/dark_avatar.png' is not in list

`$ cd /tmp;vimiv dark_avatar.png` works fine.

**Comment by karlch** [comment]
I think this was solved in the commit I pushed about 2 minutes ago, would you mind testing with the newest version?

**Comment by andresmrm** [comment]
It works! Thanks! =D
