### ISSUE TITLE
Some error while running

### ISSUE THREAD

**Issue by alexandry-augustin** [karlch/vimiv#45]
Hi, I simply run the code by ./vimiv.py on the latest dev and error occurred:

> Traceback (most recent call last):
>   File "./vimiv.py", line 6, in <module>
>     from vimiv.app import Vimiv
>   File "/home/alex/shared/cs/my_projects/tiled_filemanager/vimiv/vimiv/app.py", line 25, in <module>
>     from vimiv.thumbnail import Thumbnail
>   File "/home/alex/shared/cs/my_projects/tiled_filemanager/vimiv/vimiv/thumbnail.py", line 168
>     
>          ^
> SyntaxError: only named arguments may follow *expression
> 

which correspond to the following code
```
# Add initial placeholder for all thumbnails
default_pixbuf_max = GdkPixbuf.Pixbuf.new_from_file_at_scale(
      self.thumbnail_manager.default_icon,
      *self.get_zoom_level(), True)
```

I have tried with python 2 and 3.

Is seems that something is wrong with the unpacking.

**Comment by karlch** [comment]
What python3 version are you running? Anything older than python 3.5 is not officially supported, as I only provide support up to the latest Ubuntu LTS release (currently Ubuntu 16.04 with python 3.5.1).
